//
//  SRConstSports.h
//  SRSDK
//
//  Copyright (c) 2014 Sportradar AG All rights reserved.
//
typedef enum _SRConstSports {
	SPORT_SOCCER = 1,
	SPORT_BASKETBALL = 2,
	SPORT_BASEBALL = 3,
	SPORT_ICE_HOKEY = 4,
	SPORT_TENNIS = 5,
	SPORT_HANDBALL = 6,
	SPORT_FLOORBALL = 7,
	SPORT_MOTORSPORT = 11,
	SPORT_RUGBY = 12,
	SPORT_AUSSIE_RULES = 13,
	SPORT_BANDY = 15,
	SPORT_AMERICAN_FOOTBALL = 16,
	SPORT_SNOOKER = 19,
    SPORT_TABLE_TENNIS = 20,
	SPORT_DARTS = 22,
	SPORT_VOLLEYBALL = 23,
	SPORT_FIELD_HOCKEY = 24,
	SPORT_WATERPOLO = 26,
	SPORT_FUTSAL = 29,
    SPORT_BADMINTON = 31,
	SPORT_BEACH_VOLLEY = 34,
	SPORT_SOFTBALL = 54,
	SPORT_UNKNOWN = -1
    
} SRConstSports;

