//
//  SRConstMatchStatuses.h
//  SRSDK
//
//  Copyright (c) 2014 Sportradar AG All rights reserved.
//
typedef enum _SRConstMatchStatuses {
	MATCHSTATUS_UNKNOWN = -1,
	MATCHSTATUS_NOT_STARTED = 0,
	MATCHSTATUS_FIRST_PERIOD = 1,
	MATCHSTATUS_SECOND_PERIOD = 2,
	MATCHSTATUS_THIRD_PERIOD = 3,
	MATCHSTATUS_FOURTH_PERIOD = 4,
	MATCHSTATUS_FIFTH_PERIOD = 5,
	MATCHSTATUS_FIRST_HALF = 6,
	MATCHSTATUS_SECOND_HALF = 7,
	MATCHSTATUS_FIRST_SET = 8,
	MATCHSTATUS_SECOND_SET = 9,
	MATCHSTATUS_THIRD_SET = 10,
	MATCHSTATUS_FOURTH_SET = 11,
	MATCHSTATUS_FIFTH_SET = 12,
	MATCHSTATUS_FIRST_QUARTER = 13,
	MATCHSTATUS_SECOND_QUARTER = 14,
	MATCHSTATUS_THIRD_QUARTER = 15,
	MATCHSTATUS_FOURTH_QUARTER = 16,
	MATCHSTATUS_GOLDEN_SET = 17,
	MATCHSTATUS_STARTED = 20,
	MATCHSTATUS_PAUSED = 30,
	MATCHSTATUS_HALFTIME = 31,
	MATCHSTATUS_AWAITING_EXTRA_TIME = 32,
	MATCHSTATUS_EXTRA_TIME_HALFTIME = 33,
	MATCHSTATUS_AWAITING_PENALTIES = 34,
    MATCHSTATUS_AWAITING_PENALTIES_ICE_HOCKEY = 35,
	MATCHSTATUS_OVERTIME = 40,
	MATCHSTATUS_FIRST_EXTRA = 41,
	MATCHSTATUS_SECOND_EXTRA = 42,
	MATCHSTATUS_PENALTIES = 50,
    MATCHSTATUS_PENALTIES_NOT_SOCCER = 51,
    MATCHSTATUS_PENALTIES_ICE_HOCKEY = 52,
	MATCHSTATUS_POSTPONED = 60,
	MATCHSTATUS_START_DELAYED = 61,
	MATCHSTATUS_CANCELLED = 70,
    MATCHSTATUS_GAME_1 = 71,        // table tennis
    MATCHSTATUS_GAME_2 = 72,        // table tennis
    MATCHSTATUS_GAME_3 = 73,        // table tennis
    MATCHSTATUS_GAME_4 = 74,        // table tennis
    MATCHSTATUS_GAME_5 = 75,        // table tennis
    MATCHSTATUS_GAME_6 = 76,        // table tennis
    MATCHSTATUS_GAME_7 = 77,        // table tennis
	MATCHSTATUS_INTERRUPTED = 80,
	MATCHSTATUS_SUSPENDED = 81,
	MATCHSTATUS_ABANDONED = 90,
	MATCHSTATUS_WALKOVER = 91,
	MATCHSTATUS_RETIRED = 92,
	MATCHSTATUS_WALKOVER_PLAYER1_WON = 93,
	MATCHSTATUS_WALKOVER_PLAYER2_WON = 94,
	MATCHSTATUS_PLAYER1_RETIRED = 95,
	MATCHSTATUS_PLAYER2_RETIRED = 96,
	MATCHSTATUS_ONLY_RESULT = 99,
	MATCHSTATUS_ENDED = 100,
	MATCHSTATUS_AFTER_EXTRA_TIME = 110,
	MATCHSTATUS_AFTER_PENALTIES = 120,
    MATCHSTATUS_AFTER_PENALTIES_NOT_SOCCER = 121,
	MATCHSTATUS_AFTER_PENALTIES_ICE_HOCKEY = 125,
	MATCHSTATUS_AGS = 130,
	MATCHSTATUS_FIRST_BREAK = 301,
	MATCHSTATUS_SECOND_BREAK = 302,
	MATCHSTATUS_THIRD_BREAK = 303,
	MATCHSTATUS_FOURTH_BREAK = 304,
    MATCHSTATUS_SNOOKER_BREAK = 445
} SRConstMatchStatuses;

