//
//  SRConstPlayerCurrentPosition.h
//  SRSDK
//
//  Copyright (c) 2014 Sportradar AG All rights reserved.
//
typedef enum _SRConstPlayerCurrentPosition {
	POSITION_CURRENT_UNKNOWN = 0,
	POSITION_CURRENT_GOALKEEPER = 1,
	POSITION_CURRENT_RIGHT_BACK = 2,
	POSITION_CURRENT_CENTRAL_DEFENDER = 3,
	POSITION_CURRENT_LEFT_BACK = 4,
	POSITION_CURRENT_RIGHT_WINGER = 5,
	POSITION_CURRENT_CENTRAL_MIDFIELDER = 6,
	POSITION_CURRENT_LEFT_WINGER = 7,
	POSITION_CURRENT_STRIKER = 8
} SRConstPlayerCurrentPosition;

