//
//  SRConstStatistics.h
//  SRSDK
//
//  Copyright (c) 2014 Sportradar AG All rights reserved.
//
typedef enum _SRConstStatistics {
    STATISTICS_UNKNOWN = -1,
	STATISTICS_YELLOW_CARDS = 0,
	STATISTICS_YELLOW_RED_CARDS = 1,
	STATISTICS_RED_CARDS = 2,
	STATISTICS_SUBSTITUTIONS = 3,
	STATISTICS_BALL_POSSESSION = 4,
	STATISTICS_FREE_KICKS = 5,
	STATISTICS_GOAL_KICKS = 6,
	STATISTICS_THROW_INS = 7,
	STATISTICS_OFFSIDES = 8,
	STATISTICS_CORNER_KICKS = 9,
	STATISTICS_SHOT_ON_TARGET = 10,
	STATISTICS_SHOT_OFF_TARGET = 11,
	STATISTICS_SAVES = 12,
	STATISTICS_FOULS = 13,
	STATISTICS_INJURIES = 14,
	STATISTICS_SHOTS_BLOCKED = 15,
    STATISTICS_ACES = 16,
    STATISTICS_DOUBLE_FAULTS = 17,
	STATISTICS_MAX_POINTS = 18,
	STATISTICS_WON_POINTS = 19,
    STATISTICS_FIRST_SERVE_SUCCESSFUL = 20,
	STATISTICS_FIRST_SERVE_POINTS_WON = 21,
	STATISTICS_BREAK_POINTS_WON = 22,
	STATISTICS_SERVING_POINTS = 23,
	STATISTICS_BREAK_POINTS = 24,
	STATISTICS_MAX_GAMES = 25,
	STATISTICS_SERVER_GAMES = 26,
	STATISTICS_DANGEROUS_ATTTACK = 27,
	STATISTICS_BALL_SAFE = 28,
	STATISTICS_FREE_THROWS_SCORED = 29,
    STATISTICS_REBOUNDS = 30,
    STATISTICS_SEVEN_METERS_SCORED,
    STATISTICS_TIMEOUTS,
	STATISTICS_ATTACK,
	STATISTICS_TIEBREAKS_WON,
	STATISTICS_SECOND_SERVE_POINTS_WON,
	STATISTICS_GOAL_ATTEMPTS,
	STATISTICS_GAMES_TWO_POINTERS,
	STATISTICS_GAMES_THREE_POINTERS,
	STATISTICS_GAMES_SUCCSESS_ATTEMPTS,
	STATISTICS_GAMES_WON,
    STATISTICS_RECEIVER_POINTS_WON,             // volleyball
    STATISTICS_SERVICE_ERRORS,                  // volleyball
    STATISTICS_GOALS_IN_POWERPLAY,              // ice hockey
    STATISTICS_GOALS_SHORT_HANDED,
    STATISTICS_POWERPLAYS,
    STATISTICS_PENALTIES,
    STATISTICS_COMEBACK_TO_WIN,                 // badminton
    STATISTICS_BIGGEST_LEAD,                    // badminton
    STATISTICS_TIME_SPENT_IN_LEAD,              // basketball
    STATISTICS_LEAD_CHANGES,                    // basketball
    STATISTICS_TRIES,                           // rugby
    STATISTICS_CONVERSIONS,                     // rugby
    STATISTICS_DROP_GOALS,                      // rugby
    STATISTICS_SCRUMS,                          // rugby
    STATISTICS_PENALTY_GOALS,                   // rugby
    STATISTICS_PENALTIES_CONCEDED,              // rugby
} SRConstStatistics;
