//
//  SRConstMatchScoreTypes.h
//  SRSDK
//
//  Copyright (c) 2014 Sportradar AG All rights reserved.
//
typedef enum _SRConstMatchScoreTypes {
	MATCHSCORE_UNKNOWN = 0,
	MATCHSCORE_SCORE = 1,
	MATCHSCORE_HALFTIME = 2,
	MATCHSCORE_FULLTIME = 3,
	MATCHSCORE_EXTRATIME = 4,
	MATCHSCORE_PENALTIES = 5,
	MATCHSCORE_PERIOD_1 = 6,
	MATCHSCORE_PERIOD_2 = 7,
	MATCHSCORE_PERIOD_3 = 8,
	MATCHSCORE_PERIOD_4 = 9,
	MATCHSCORE_PERIOD_5 = 10,
	MATCHSCORE_PERIOD_6 = 11,
	MATCHSCORE_PERIOD_7 = 12,
	MATCHSCORE_PERIOD_8 = 13,
	MATCHSCORE_PERIOD_9 = 14,
	MATCHSCORE_AGGREGATE = 15
} SRConstMatchScoreTypes;

