//
//  SRConstStatistics.h
//  SRSDK
//
//  Copyright (c) 2014 Sportradar AG All rights reserved.
//

typedef NS_ENUM(NSUInteger, SRConstStatistics) {
    STATISTICS_UNKNOWN=0,
	STATISTICS_YELLOW_CARDS,
	STATISTICS_YELLOW_RED_CARDS,
	STATISTICS_RED_CARDS,
	STATISTICS_SUBSTITUTIONS,
	STATISTICS_BALL_POSSESSION,
	STATISTICS_FREE_KICKS,
	STATISTICS_GOAL_KICKS,
	STATISTICS_THROW_INS,
	STATISTICS_OFFSIDES,
	STATISTICS_CORNER_KICKS,
	STATISTICS_SHOT_ON_TARGET,
	STATISTICS_SHOT_OFF_TARGET,
	STATISTICS_SAVES,
	STATISTICS_FOULS,
	STATISTICS_INJURIES,
	STATISTICS_SHOTS_BLOCKED,
    STATISTICS_ACES,
    STATISTICS_DOUBLE_FAULTS,
	STATISTICS_MAX_POINTS,
	STATISTICS_WON_POINTS,
    STATISTICS_FIRST_SERVE_SUCCESSFUL,
	STATISTICS_FIRST_SERVE_POINTS_WON,
	STATISTICS_BREAK_POINTS_WON,
	STATISTICS_SERVING_POINTS,
	STATISTICS_BREAK_POINTS,
	STATISTICS_MAX_GAMES,
	STATISTICS_SERVER_GAMES,
	STATISTICS_DANGEROUS_ATTTACK,
	STATISTICS_BALL_SAFE,
	STATISTICS_FREE_THROWS_SCORED,
    STATISTICS_REBOUNDS,
    STATISTICS_SEVEN_METERS_SCORED,
    STATISTICS_2_MINUTES_PENALTIES,
    STATISTICS_TIMEOUTS,
	STATISTICS_ATTACK,
	STATISTICS_TIEBREAKS_WON,
	STATISTICS_SECOND_SERVE_POINTS_WON,
	STATISTICS_GOAL_ATTEMPTS,
	STATISTICS_GAMES_TWO_POINTERS,
	STATISTICS_GAMES_THREE_POINTERS,
	STATISTICS_GAMES_SUCCSESS_ATTEMPTS,
	STATISTICS_GAMES_WON,
    STATISTICS_RECEIVER_POINTS_WON,             // volleyball
    STATISTICS_SERVICE_ERRORS,                  // volleyball
    STATISTICS_GOALS_IN_POWERPLAY,              // ice hockey
    STATISTICS_GOALS_SHORT_HANDED,
    STATISTICS_ATTACK_SUCCESS,
    STATISTICS_POWERPLAYS,
    STATISTICS_PENALTIES,
    STATISTICS_COMEBACK_TO_WIN,                 // badminton
    STATISTICS_BIGGEST_LEAD,                    // badminton
    STATISTICS_TIME_SPENT_IN_LEAD,              // basketball
    STATISTICS_LEAD_CHANGES,                    // basketball
    STATISTICS_TRIES,                           // rugby
    STATISTICS_CONVERSIONS,                     // rugby
    STATISTICS_DROP_GOALS,                      // rugby
    STATISTICS_SCRUMS,                          // rugby
    STATISTICS_PENALTY_GOALS,                   // rugby
	STATISTICS_LINEOUTS,						// rugby
	STATISTICS_PENALTY_TRIES,					// rugby
    STATISTICS_PENALTIES_CONCEDED,              // rugby
    STATISTICS_DURATION,
    
    // WARNING: This value represents number of elements in this enum. Add new elements before this one!
    NUMBER_OF_ELEMENTS
};
